### PR TITLE
Issue/639 search box in player lists

### PR DESCRIPTION
**Pull request by MinecraftXwinP**
Should Fix [#639](https://github.com/LatvianModder/FTBUtilities/issues/639).

### CODE REVIEW

**Comment by LatvianModder** [comment]
Why is there `+import javax.xml.soap.Text;`? That isn't used anywhere as far as I can tell

**Comment by MinecraftXwinP** [comment]
opss, Sorry, that was misadded by the IDE.

**Comment by LatvianModder** [comment]
Eh, still not a fan of implementation. I think I will write my own and just mention you in the commit if that's fine with you 😛  I wanted this to be implemented in every GuiButtonList base and I thought of a simplier way to do it

**Comment by MinecraftXwinP** [comment]
OK, feel free to close the PR. I think the implementation is a little by hacky too.

**Pull request closed without merging**
